services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 포트
      - "15672:15672" # 관리 인터페이스 포트
    environment:
      RABBITMQ_DEFAULT_USER: guestuser
      RABBITMQ_DEFAULT_PASS: guestuser
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
